### ISSUE TITLE
StringTemplate3StatementLocator is Incompatible with HashPrefixStatementRewriter

### ISSUE THREAD

**Issue by apjoseph** [jdbi/jdbi#248]
As a result of `SqlScriptParser` being hardcoded to remove hashes (as explained in the [class description](https://github.com/jdbi/jdbi/blob/92c843d80467d915f125904eecbb3985d57227e9/src/main/java/org/skife/jdbi/v2/SqlScriptParser.java#L23-L23)), `StringTemplate3StatementLocator` is completely and totally incompatible with `HashPrefixStatementRewriter`, which means that it is essentially incompatible with Postgres -unless one is willing to go through potentially thousands of existing scripts and replace casts with abominations like `\\:\\:bigint` or `cast(variable as bigint)`

**Comment by stevenschlansker** [comment]
Hi @apjoseph sorry, this sounds frustrating.
@arteam you contributed the new lexer, maybe you can comment here?

I wonder if the best fix is to not handle `#` comments by default, or maybe make it an option to the parsing mechanism.  It seems that `#` and `/* */` comments are not SQL standards but MySQL extensions, and would not work with Postgres anyway.

Do you have any other thoughts on an acceptable solution?

**Comment by stevenschlansker** [comment]
This probably blocks the 2.71 release :disappointed:

**Comment by apjoseph** [comment]
I ended up just creating a custom `StatementLocator` using a simple `Map` of SQL scripts that I load from various folders and using [Handlebars](https://github.com/jknack/handlebars.java)  (for more portable {{variable}} syntax) as the templating engine. I made this switch a while ago, but happened to find the bug during testing and thought I would point it out. The `@BindIn` annotation also assumes colons are used and thus suffers from the same problem.  

I think the broader ideal solution would be to make the colon parser (or another colon parser variant) able to just detect and ignore double colons and thus avoid the need to use the hash as a prefix in the first place Colons seem to be an unofficial standard for variable binding in multiple libraries across multiple languages and some users may desire to use sql templates across codebases.

**Comment by stevenschlansker** [comment]
We just fixed the double colon issue in #316 -- does this resolve the issue for you?

**Comment by stevenschlansker** [comment]
I think this issue can be closed now, please reopen if there's any followup needed.

**Comment by toadzky** [comment]
this is still happening in jdbi3 with the classpath sql locator.
