### ISSUE TITLE
JDBI no longer usable on JREs/JDKs without Java Flight Recorder classes

### ISSUE THREAD

**Issue by PascalSchumacher** [jdbi/jdbi#2736]
After updating jdbi3-core from `3.45.4` to `3.47.0` we are getting:

```
java.lang.NoClassDefFoundError: jdk.jfr.Event
	at java.base/java.lang.ClassLoader.defineClassImpl(Native Method) ~[?:?]
	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:472) ~[?:?]
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:433) ~[?:?]
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:657) ~[?:?]
	at java.base/java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1061) ~[?:?]
	at java.base/java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1046) ~[?:?]
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:784) ~[?:?]
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:572) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClassHelper(ClassLoader.java:1204) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1119) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1102) ~[?:?]
	at org.jdbi.v3.core.statement.SqlStatement.<clinit>(SqlStatement.java:76) ~[jdbi3-core-3.47.0.jar:3.47.0]
	at org.jdbi.v3.core.Handle.createQuery(Handle.java:432) ~[jdbi3-core-3.47.0.jar:3.47.0]
	at org.jdbi.v3.core.Handle.createQuery(Handle.java:444) ~[jdbi3-core-3.47.0.jar:3.47.0]
	at ourorg.OurClass
	at org.jdbi.v3.core.Jdbi.withHandle(Jdbi.java:422) ~[jdbi3-core-3.47.0.jar:3.47.0]
```

I think the problem is that we are using OpenJ9 Java 21 JDK, which does not include the Java Flight Recorder classes.

By the way: Thank you very much for developing JDBI!

**Comment by stevenschlansker** [comment]
Well this sucks. I thought all JDKs would implement flight recorder :(

I guess we will need to make this optional somehow.

**Comment by hgschmie** [comment]
there seems to be work on this for J9: https://github.com/eclipse-openj9/openj9/pulls?q=is%3Apr+is%3Aopen+jfr

But as jfr is optional for a JDK, we may need to work around this more. also, we may want to re-enable the non-temurin tests on the CI.

**Comment by gjvoosten** [comment]
Any progress on this? I'd really like to see a new release where this is fixed, as currently our jpackage'd application fails to start due to this error…

**Comment by stevenschlansker** [comment]
Sorry for the delay @gjvoosten , we hope to fix this for the next release. Henning started some work but did not complete it - if he does not return to it soon, I'll try to pick it up.

**Comment by pompiuses** [comment]
Flight Recorder is also causing problems when using GraalVM since it's disabled by default when compiling to a native image.

```
java.lang.UnsatisfiedLinkError: jdk.jfr.internal.JVM.isExcluded(Ljava/lang/Class;)Z [symbol: Java_jdk_jfr_internal_JVM_isExcluded or Java_jdk_jfr_internal_JVM_isExcluded__Ljava_lang_Class_2]
at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:152)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:54)
at jdk.jfr@21.0.4/jdk.jfr.internal.JVM.isExcluded(Native Method)
at jdk.jfr@21.0.4/jdk.jfr.internal.MetadataRepository.register(MetadataRepository.java:137)
at jdk.jfr@21.0.4/jdk.jfr.internal.MetadataRepository.register(MetadataRepository.java:132)
at jdk.jfr@21.0.4/jdk.jfr.FlightRecorder.register(FlightRecorder.java:128)
at org.jdbi.v3.core.statement.SqlStatement.<clinit>(SqlStatement.java:76)
at java.base@21.0.4/java.lang.Class.ensureInitialized(DynamicHub.java:604)
at org.jdbi.v3.core.Handle.createQuery(Handle.java:432)
at org.jdbi.v3.core.Handle.select(Handle.java:321)
at org.jdbi.v3.core.Handle.select(Handle.java:338)
...
```

**Comment by stevenschlansker** [comment]
We'll make this optional in the next release.

**Comment by stevenschlansker** [comment]
Hi @gjvoosten @pompiuses , I have a branch open with a candidate fix. If you have a moment to build and test a snapshot and verify the problem is fixed for you that would help us.

**Comment by pompiuses** [comment]
I still get the exact same error when using GraalVM. I cloned the JDBI source from branch `jfr-optional` (3.48.0-SNAPSHOT) and built it locally using Maven.

```
java.lang.UnsatisfiedLinkError: jdk.jfr.internal.JVM.isExcluded(Ljava/lang/Class;)Z [symbol: Java_jdk_jfr_internal_JVM_isExcluded or Java_jdk_jfr_internal_JVM_isExcluded__Ljava_lang_Class_2]
at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:152)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:41)
at jdk.jfr@23.0.1/jdk.jfr.internal.JVM.isExcluded(Native Method)
at jdk.jfr@23.0.1/jdk.jfr.internal.MetadataRepository.register(MetadataRepository.java:139)
at jdk.jfr@23.0.1/jdk.jfr.internal.MetadataRepository.register(MetadataRepository.java:134)
at jdk.jfr@23.0.1/jdk.jfr.FlightRecorder.register(FlightRecorder.java:129)
at org.jdbi.v3.core.statement.internal.JfrSupport.register(JfrSupport.java:39)
at org.jdbi.v3.core.statement.SqlStatement.<clinit>(SqlStatement.java:78)
at java.base@23.0.1/java.lang.Class.ensureInitialized(DynamicHub.java:650)
at org.jdbi.v3.core.Handle.createQuery(Handle.java:432)
at org.jdbi.v3.core.Handle.select(Handle.java:321)
at org.jdbi.v3.core.Handle.select(Handle.java:338)
...
```

**Comment by gjvoosten** [comment]
@stevenschlansker Unfortunately I get the same error as @pompiuses; with JDBI **3.47.0** I got:
```
Caused by: java.lang.NoClassDefFoundError: jdk/jfr/Event
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.jdbi.v3.core.statement.SqlStatement.<clinit>(SqlStatement.java:76)
	at org.jdbi.v3.core.Handle.createQuery(Handle.java:432)
	at org.jdbi.v3.core.Handle.createQuery(Handle.java:444)
        […our class…]
```
and with **3.48.0-SNAPSHOT** built from the _jfr-optional_ branch I get:
```
Caused by: java.lang.NoClassDefFoundError: jdk/jfr/Event
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unknown Source)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.jdbi.v3.core.statement.SqlStatement.<clinit>(SqlStatement.java:78)
	at org.jdbi.v3.core.Handle.createQuery(Handle.java:432)
	at org.jdbi.v3.core.Handle.createQuery(Handle.java:444)
        […our class…]
```
(spot the different line number in `SqlStatement.java`).

**Comment by stevenschlansker** [comment]
Sorry, indeed, my mistake. I updated the PR with another attempt. If you have time to check again, that'd be much appreciated - I wish it was easier to test classes not being present...

**Comment by pompiuses** [comment]
Still the same error.

```
java.lang.UnsatisfiedLinkError: jdk.jfr.internal.JVM.isExcluded(Ljava/lang/Class;)Z [symbol: Java_jdk_jfr_internal_JVM_isExcluded or Java_jdk_jfr_internal_JVM_isExcluded__Ljava_lang_Class_2]
at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:152)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:41)
at jdk.jfr@23.0.1/jdk.jfr.internal.JVM.isExcluded(Native Method)
at jdk.jfr@23.0.1/jdk.jfr.internal.MetadataRepository.register(MetadataRepository.java:139)
at jdk.jfr@23.0.1/jdk.jfr.internal.MetadataRepository.register(MetadataRepository.java:134)
at jdk.jfr@23.0.1/jdk.jfr.FlightRecorder.register(FlightRecorder.java:129)
at org.jdbi.v3.core.statement.internal.JfrSupport$Holder.registerEvents(JfrSupport.java:46)
at org.jdbi.v3.core.statement.internal.JfrSupport.registerEvents(JfrSupport.java:31)
at org.jdbi.v3.core.statement.SqlStatement.<clinit>(SqlStatement.java:78)
at java.base@23.0.1/java.lang.Class.ensureInitialized(DynamicHub.java:650)
at org.jdbi.v3.core.Handle.createQuery(Handle.java:432)
at org.jdbi.v3.core.Handle.select(Handle.java:321)
at org.jdbi.v3.core.Handle.select(Handle.java:338)
...
```

**Comment by pompiuses** [comment]
If I explicitly enable JFR, [per the docs](https://www.graalvm.org/latest/reference-manual/native-image/overview/Options/), when GraalVM compiles the native binary it works ok.

`--enable-monitoring=jfr`

However this is turned off by default, and should only be enabled when strictly needed. Maybe the JFR support should be in a separate module/dependency?

**Comment by stevenschlansker** [comment]
Thanks @pompiuses for checking again. This is surprising to me, as I think it means our check:
```
ModuleLayer.boot().findModule("jdk.jfr").isPresent()
```
actually returns `true` despite the classes in that module not being available. Strange.
Must be related to them being "excluded" by graal as opposed to not available at all.

I appreciate your point about a separate dependency. The idea was that JFR is supposed to be zero-overhead when off, so it would be nice to include by default for most Jdbi users on a JDK that supports it. Obviously the first pass didn't go as smoothly as we liked :) If we can't get this working smoothly, we'll move it to a separate module.


I changed the open PR to test if `Class.forName("jdk.jfr.FlightRecorder")` succeeds instead of trying to check for a module.
Would you please humor me with checking one more time? 🤞 this time works

**Comment by stevenschlansker** [comment]
Ah yes, it is actually a different error entirely:
```
java.lang.UnsatisfiedLinkError: jdk.jfr.internal.JVM.isExcluded(Ljava/lang/Class;)Z [symbol: Java_jdk_jfr_internal_JVM_isExcluded or Java_jdk_jfr_internal_JVM_isExcluded__Ljava_lang_Class_2]
at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:152)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:41)
at jdk.jfr@23.0.1/jdk.jfr.internal.JVM.isExcluded(Native Method)
at jdk.jfr@23.0.1/jdk.jfr.internal.MetadataRepository.register(MetadataRepository.java:139)
at jdk.jfr@23.0.1/jdk.jfr.internal.MetadataRepository.register(MetadataRepository.java:134)
at jdk.jfr@23.0.1/jdk.jfr.FlightRecorder.register(FlightRecorder.java:129)
```

so the module and class are actually present, but throw if you try to use them.

**Comment by stevenschlansker** [comment]
I updated the PR to also try to catch this `UnsatisfiedLinkError`.

**Comment by stevenschlansker** [comment]
Ok, it's a little frustrating that they leave JFR in such a broken state (it explicitly exists, the API allows it to be turned off at any time, and it blows up instead...) 

I updated to a new version that tries to register and catch the link error, and avoid any references to events. I hope it works or at least we get a different error now 😁

**Comment by pompiuses** [comment]
Still get same error as my last post.

```
java.lang.UnsatisfiedLinkError: jdk.jfr.internal.JVM.isExcluded(Ljava/lang/Class;)Z [symbol: Java_jdk_jfr_internal_JVM_isExcluded or Java_jdk_jfr_internal_JVM_isExcluded__Ljava_lang_Class_2]
at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:152)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:41)
at jdk.jfr@23.0.1/jdk.jfr.internal.JVM.isExcluded(Native Method)
at jdk.jfr@23.0.1/jdk.jfr.internal.MetadataRepository.register(MetadataRepository.java:139)
at jdk.jfr@23.0.1/jdk.jfr.internal.MetadataRepository.register(MetadataRepository.java:134)
at jdk.jfr@23.0.1/jdk.jfr.FlightRecorder.register(FlightRecorder.java:129)
at org.jdbi.v3.core.statement.JdbiStatementEvent.<clinit>(JdbiStatementEvent.java)
at org.jdbi.v3.core.statement.SqlStatement.internalExecute(SqlStatement.java:1795)
at org.jdbi.v3.core.result.ResultProducers.lambda$createResultBearing$3(ResultProducers.java:96)
at org.jdbi.v3.core.result.internal.ResultSetSupplier.get(ResultSetSupplier.java:55)
at org.jdbi.v3.core.result.internal.ResultSetResultIterator.<init>(ResultSetResultIterator.java:52)
at org.jdbi.v3.core.result.internal.ResultSetResultIterable.iterator(ResultSetResultIterable.java:51)
at org.jdbi.v3.core.result.ResultIterable.stream(ResultIterable.java:266)
at org.jdbi.v3.core.result.ResultIterable.collect(ResultIterable.java:340)
...
```

Problem:
The class SqlStatement.java#1795 tries to create a new object of JdbiStatementEvent.java which in turn imports annotations from the JFR package.

As I said in the previous post you cannot import any classes, or in this case annotations, from the package "jdk.jfr.*" since they do not exist on the classpath.

**Comment by stevenschlansker** [comment]
Hi @pompiuses , yes I understand that, somehow I must have messed up my last push??? because I definitely fixed this issue but the PR did not update with my change :( My apologies for that. I've applied the following change to this line, which should avoid loading that class:

```
     PreparedStatement internalExecute() {
         final StatementContext ctx = getContext();
-        final JdbiStatementEvent evt = new JdbiStatementEvent();
+        final OptionalEvent evt = JfrSupport.newStatementEvent();
         evt.begin();
```

BTW, if it's easy for you to share your test case, I'm happy to try it myself - but I don't have a Graal environment ready to go so it's hard for me to test this myself. Thanks for your continued support here.

**Comment by pompiuses** [comment]
Your last commit did the trick, it now works ok. Good stuff!

**Comment by stevenschlansker** [comment]
Hi @PascalSchumacher @pompiuses this should be fixed in the newly released 3.48.0.
Thanks for reporting this issue.

**Comment by pompiuses** [comment]
Yes, 3.48.0 works ok with GraalVM. Thanks!

**Comment by pompiuses** [comment]
I just upgraded to 3.49.1 and this error is back (using GraalVM).

```
java.lang.ExceptionInInitializerError
at org.jdbi.v3.core.statement.internal.JfrSupport.<clinit>(JfrSupport.java:41)
at org.jdbi.v3.core.statement.SqlStatement.internalExecute(SqlStatement.java:1791)
at org.jdbi.v3.core.result.ResultProducers.lambda$createResultBearing$3(ResultProducers.java:96)
at org.jdbi.v3.core.result.internal.ResultSetSupplier.get(ResultSetSupplier.java:55)
at org.jdbi.v3.core.result.internal.ResultSetResultIterator.<init>(ResultSetResultIterator.java:53)
at org.jdbi.v3.core.result.internal.ResultSetResultIterable.iterator(ResultSetResultIterable.java:51)
at org.jdbi.v3.core.result.ResultIterable.stream(ResultIterable.java:266)
at org.jdbi.v3.core.result.ResultIterable.collect(ResultIterable.java:340)
...
Caused by: java.lang.reflect.InvocationTargetException
at java.base@23.0.2/java.lang.reflect.Method.invoke(Method.java:580)
at org.jdbi.v3.core.statement.internal.JfrSupport.<clinit>(JfrSupport.java:35)
... 27 more
Caused by: java.lang.UnsatisfiedLinkError: jdk.jfr.internal.JVM.isExcluded(Ljava/lang/Class;)Z [symbol: Java_jdk_jfr_internal_JVM_isExcluded or Java_jdk_jfr_internal_JVM_isExcluded__Ljava_lang_Class_2]
at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:152)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:41)
at jdk.jfr@23.0.2/jdk.jfr.internal.JVM.isExcluded(Native Method)
at jdk.jfr@23.0.2/jdk.jfr.internal.MetadataRepository.register(MetadataRepository.java:139)
at jdk.jfr@23.0.2/jdk.jfr.internal.MetadataRepository.register(MetadataRepository.java:134)
at jdk.jfr@23.0.2/jdk.jfr.FlightRecorder.register(FlightRecorder.java:129)
... 29 more

```

**Comment by hgschmie** [comment]
Yes, I made some changes to the JFR support (we actually added CI using the Semeru JDK which does not support JFR). It seems we need to test with Graal as well.

**Comment by stevenschlansker** [comment]
I still want to add GraalVM to CI tests (over in #2476 ) but it is not quite ready yet.

**Comment by pompiuses** [comment]
I get a different error on 3.49.2.

```
java.lang.UnsatisfiedLinkError: jdk.jfr.internal.JVM.isExcluded(Ljava/lang/Class;)Z [symbol: Java_jdk_jfr_internal_JVM_isExcluded or Java_jdk_jfr_internal_JVM_isExcluded__Ljava_lang_Class_2]
at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:152)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:41)
at jdk.jfr@24.0.1/jdk.jfr.internal.JVM.isExcluded(Native Method)
at jdk.jfr@24.0.1/jdk.jfr.internal.MetadataRepository.register(MetadataRepository.java:139)
at jdk.jfr@24.0.1/jdk.jfr.internal.MetadataRepository.register(MetadataRepository.java:134)
at jdk.jfr@24.0.1/jdk.jfr.FlightRecorder.register(FlightRecorder.java:127)
at org.jdbi.v3.core.statement.JdbiStatementEvent.<clinit>(JdbiStatementEvent.java)
at org.jdbi.v3.core.statement.internal.JfrSupport$Holder.newEvent(JfrSupport.java:67)
at org.jdbi.v3.core.statement.internal.JfrSupport.newStatementEvent(JfrSupport.java:57)
at org.jdbi.v3.core.statement.SqlStatement.internalExecute(SqlStatement.java:1791)
at org.jdbi.v3.core.result.ResultProducers.lambda$createResultBearing$4(ResultProducers.java:110)
at org.jdbi.v3.core.result.internal.ResultSetSupplier.get(ResultSetSupplier.java:55)
at org.jdbi.v3.core.result.internal.ResultSetResultIterator.<init>(ResultSetResultIterator.java:53)
at org.jdbi.v3.core.result.internal.ResultSetResultIterable.iterator(ResultSetResultIterable.java:51)
at org.jdbi.v3.core.result.ResultIterable.stream(ResultIterable.java:266)
at org.jdbi.v3.core.result.ResultIterable.collect(ResultIterable.java:340)
at no.nhn.hit.authorization.kjernejournal.infrastructure.KjSikkerhetDb.lambda$getActiveTicketKeys$0(KjSikkerhetDb.java:49)
at org.jdbi.v3.core.Jdbi.withHandle(Jdbi.java:422)
...

```

**Comment by stevenschlansker** [comment]
@hgschmie , looks like it is still not working... :(

**Comment by hgschmie** [comment]
@pompiuses do you have a very small test that uses graalvm to compile? It is very much hit and miss to figure out what Graalvm suports and what not.

**Comment by stevenschlansker** [comment]
If I recall correctly from my experiments, basically any test that tries to load jdbi code in native-tests will fail, since it runs as part of initialization.

**Comment by pompiuses** [comment]
@hgschmie Making a test case is not that easy as it requires infrastructure to be setup.

Steps to reproduce:
- Download the GraalVM JDK.
- Create a small application which uses JDBI to connect to a database and does a query.
- Compile the application to a native binary.
- Start the native binary.
- The error occurs at runtime when the application queries the database.

Yes, adding `--enable-monitoring=jfr` would work, but that will add runtime overhead and increase the size of the binary. That's why it's disabled by default by GraalVM. As @stevenschlansker mentioned above JDBI should work without requiring JFR.

**Comment by hgschmie** [comment]
I am fairly certain that this was caused by a bug which has been addressed by 3.49.3 (this release exists to only fix that bug :-) ) 

Please try and let us know; I'd like to put this issue to bed. Apologies for the multiple iterations.

**Comment by pompiuses** [comment]
I can confirm that 3.49.3 works OK.
